DROP DATABASE test;

CREATE DATABASE test;

USE test;

CREATE TABLE `test`.`books` (
  `ID`          INT          NOT NULL AUTO_INCREMENT,
  `BOOK_TITLE`  VARCHAR(255) NOT NULL,
  `BOOK_AUTHOR` VARCHAR(100) NOT NULL,
  `BOOK_PRICE`  INT          NOT NULL,
  `BOOK_ISBN` VARCHAR(20) NOT NULL,
  `BOOK_PRINTYEAR` INT NOT NULL,
  `BOOK_READALREADY` TINYINT(0) NOT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

